// keep/docfile.js — generate a minimal, self-contained PDF for a demo document.
// The Keep's documents are sample records with no real stored file, so the
// download button produces a clearly-labeled placeholder PDF (named after the
// document) rather than pretending to serve a confidential file. Pure + tested.

// Keep text to printable ASCII so byte length == char length (the PDF /Length
// and xref offsets are computed from string length) and escape PDF specials.
function pdfText(s) {
  return String(s == null ? "" : s)
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/[\\()]/g, (c) => "\\" + c);
}

// Build a single-page PDF (returned as a latin1 byte-string) showing `lines`,
// the first rendered as a heading. Callers convert to a Blob for download.
export function buildPdf(lines) {
  const rows = (Array.isArray(lines) ? lines : [lines]).filter((l) => l != null);
  let y = 730;
  const content = rows.map((ln, i) => {
    const size = i === 0 ? 18 : 11;
    const op = `BT /F1 ${size} Tf 72 ${y} Td (${pdfText(ln)}) Tj ET`;
    y -= i === 0 ? 32 : 18;
    return op;
  }).join("\n");

  const objs = [
    "<</Type/Catalog/Pages 2 0 R>>",
    "<</Type/Pages/Kids[3 0 R]/Count 1>>",
    "<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>",
    "<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
    `<</Length ${content.length}>>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((off) => { pdf += String(off).padStart(10, "0") + " 00000 n \n"; });
  pdf += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xrefStart}\n%%EOF`;
  return pdf;
}

// A policy document is either a plain name string (legacy) or a typed record
// { name, kind }. These readers accept both so views never care which shape a
// row is in — the single place document identity is read from.
export function docName(doc) {
  return typeof doc === "string" ? doc : (doc && doc.name) || "";
}
export function docKind(doc) {
  return typeof doc === "string" ? "" : (doc && doc.kind) || "";
}

// Body lines for a document placeholder, given its name + context (policy, asset…).
export function docLines(name, context) {
  return [
    name,
    ...(context || []).filter(Boolean),
    "",
    "Demo document generated by The Keep.",
    "This is a placeholder — no confidential policy data is included.",
  ];
}
