// keep/views/help-view.js — the Help desk page (#/keep/help, feature 003).
//
// Ask a question in plain language, get an answer from the app's help guide and
// your own records. The page's job beyond rendering is FR-10 and FR-8's UI half:
// it labels every answer AI-generated and offers the broker channel, and it does
// so UNCONDITIONALLY — never off a flag the model controls. Of the three places
// the fact/advice boundary is defended (plan, Key decision 3), this is the ONLY
// independent one: the prompt rules and the shape of the grounding both resolve
// through the same single inference, so they lower the odds and cannot catch a
// violation. This file is what still holds when that inference goes wrong.
import { el, mount } from "../../dom.js";
import { icon } from "../../icons.js";
import { askHelp, loadHelpGuide, getUser } from "../../supabase.js";
import {
  cleanQuestion, validateQuestion, suggestionChips, answerShape, creditedTopics,
} from "../logic/help.js";
import { page, originBackRow } from "./shell.js";

// FR-10's sentence, in ONE place. It is shown up front (before any question, so
// the client knows what they are reading before they type) and again on every
// answer. Two surfaces, one string — a label the user sees only after asking
// cannot inform the decision to ask.
const AI_NOTE =
  "Answers are AI-generated by Anthropic from this app's help guide and a summary " +
  "of your own records — check anything important with your broker.";

// The last answer, kept across navigations. FR-11 invites the client to follow a
// credited source to check it; the back control then promises "Back to help" —
// and the page they returned to was empty, because all state lived in this
// function's closure. Checking the answer cost the answer, and re-asking cost
// another paid call and one of twenty hourly slots.
//
// ⚠️ STAMPED WITH THE OWNER, and restored only to that owner. Module state
// outlives a sign-out: without this, signing out and signing in as someone else
// in the same tab showed the previous client's question, their answer, and their
// record lines under "Based on". This repo publishes three demo credentials and
// the login screen prefills one, so "a different person signs in on this
// machine" is the ordinary case, not a contrived one. Flagged by a security
// review of the commit that added the cache.
let lastAsk = null;

export async function renderKeepHelp() {
  const guide = await loadHelpGuide();

  const input = el("input", {
    class: "k-help__input",
    attrs: { type: "text", placeholder: "Ask a question…", "aria-label": "Ask a question", autocomplete: "off" },
  });
  const submit = el("button", { class: "k-btn k-help__ask", attrs: { type: "submit" } }, [el("span", { text: "Ask" })]);
  const error = el("p", { class: "k-error", attrs: { role: "alert" } });
  const answerRegion = el("div", { class: "k-help__out", attrs: { "aria-live": "polite" } }, [
    el("p", { class: "k-help__ai", text: AI_NOTE }),
  ]);

  // One in-flight request at a time. A second ask aborts the first rather than
  // racing it — two answers arriving out of order would render the older one.
  let inFlight = null;

  // The chips are disabled too, not just the input and the button. Aborting the
  // in-flight request only drops the BROWSER's side of it: the Edge Function has
  // already reserved a throttle row and may have started the provider call, and
  // that keeps running. So a second ask does not replace the first, it adds to
  // it — the UI said "one in flight" while the client was billed for several and
  // burned several throttle slots. Populated by renderChips() below, which runs
  // after this is defined.
  const chipButtons = [];
  function setBusy(busy) {
    submit.disabled = busy;
    input.disabled = busy;
    for (const b of chipButtons) b.disabled = busy;
    submit.querySelector("span").textContent = busy ? "Asking…" : "Ask";
  }

  function renderNotice(shaped) {
    answerRegion.replaceChildren(
      el("div", { class: "k-help__notice" }, [
        icon("alert", { size: 18 }),
        el("p", { text: shaped.notice }),
      ]),
      // The standing label lives IN this region, so replacing the region removed
      // it — leaving the failure state as the one screen with no AI-generated
      // line on it. Re-rendered rather than moved out, so there is still exactly
      // one on screen in every state.
      el("p", { class: "k-help__ai", text: AI_NOTE }),
    );
  }

  function renderAnswer(shaped, question) {
    const used = creditedTopics(guide, shaped.topics);
    const blocks = [
      el("p", { class: "k-help__q", text: question }),
      // `white-space: pre-line` in keep.css — the answer may carry line breaks
      // and collapsing them would run separate points together.
      el("div", { class: "k-help__a" }, [el("p", { text: shaped.answer })]),
    ];

    // FR-11: name what it drew on, so the client can check it.
    if (used.length || shaped.records.length) {
      blocks.push(el("div", { class: "k-help__src" }, [
        el("div", { class: "k-lbl", text: "Based on" }),
        ...used.map((t) => el("a", { class: "k-ilink", attrs: { href: t.route }, text: t.title })),
        ...shaped.records.map((r) => el("span", { class: "k-imuted", text: r })),
      ]));
    }

    // FR-8's hand-off, on EVERY answer. Nothing reads `reason === "refused"` here
    // and nothing should: the model sets it, so gating the remedy on it let a
    // model answer a coverage question AND attach "this needs your broker"
    // underneath, which reads as broker-endorsed. The trailer still carries it
    // and the payload still reports it — for logging and for anyone auditing how
    // often the boundary fires — but it decides nothing the client sees.
    //
    // That flag is model-controlled end to end: the model emits the REFUSED
    // marker, the function turns it into `reason: "refused"`, help.js turns that
    // into `brokerHandoff`, and this block appeared. Both error directions are
    // reachable and one is worse than having no hand-off at all:
    //   · declines in prose, omits the marker → the client is refused with no
    //     broker channel, so FR-8's remedy is silently absent;
    //   · answers a coverage question AND emits the marker → "This one needs your
    //     broker" renders UNDERNEATH a coverage determination, which reads as
    //     broker-endorsed. Measured. And a client can ask for that marker.
    // Unconditional removes both, and a standing "your broker can put it in
    // writing" is the right thing on an insurance help desk anyway. `reason`
    // still carries the distinction for anyone who needs it; nothing the model
    // says decides what the client is offered.
    blocks.push(el("div", { class: "k-help__broker" }, [
      el("p", { text: "Coverage questions — whether something is covered, or whether a limit is enough — are your broker's to answer in writing." }),
      el("a", { class: "k-ilink", attrs: { href: "#/keep/insurance" }, text: "Open a policy to send a request" }),
    ]));

    // FR-10, rendered on EVERY answer regardless of what came back. A model that
    // ignored its instructions cannot remove this line, which is the point.
    blocks.push(el("p", { class: "k-help__ai", text: AI_NOTE }));
    answerRegion.replaceChildren(...blocks);
  }

  async function ask(raw) {
    // cleanQuestion, NOT the raw value: the migration's CHECK caps the RAW text
    // at 500 while testing non-blankness on the TRIMMED text, so validating one
    // ⚠️ the "stored column" this once named is gone — help_queries no longer
    // keeps the question text. `handler.ts`'s QUESTION_MAX is the authority now.
    // string and sending another is how a question passes here and is refused by
    // the INSERT. One normalisation, used for both.
    const question = cleanQuestion(raw);
    const v = validateQuestion(question);
    error.textContent = v.ok ? "" : v.error;
    if (!v.ok) { input.focus(); return; }

    if (inFlight) inFlight.abort();
    const controller = new AbortController();
    inFlight = controller;
    setBusy(true);
    // The AI label rides along: replacing the whole region removed it for the
    // length of the request (up to the provider timeout), while this file's own
    // header and S10 both describe it as unconditional. "Unconditional" has to
    // include the state the client spends the most time looking at.
    answerRegion.replaceChildren(
      el("p", { class: "k-imuted", text: "Looking…" }),
      el("p", { class: "k-help__ai", text: AI_NOTE }),
    );

    const payload = await askHelp(question, { signal: controller.signal });
    if (controller.signal.aborted) return;        // superseded by a newer ask
    inFlight = null;
    setBusy(false);

    const shaped = answerShape(payload);
    lastAsk = { shaped, question, owner: getUser()?.id ?? null };
    if (shaped.ok) renderAnswer(shaped, question); else renderNotice(shaped);

    // Disabling the focused control drops focus to <body>, and nothing put it
    // back — so after one question a keyboard or screen-reader user had to tab
    // from the top of the page (bar, nav, search, two menus) to ask another.
    // Restored only when WE are the ones who dropped it: if the reader has tabbed
    // somewhere else while waiting, stealing focus back is worse than the bug.
    if (document.activeElement === document.body) input.focus();
  }

  const form = el("form", { class: "k-help__form", attrs: { novalidate: "novalidate" },
    on: { submit: (e) => { e.preventDefault(); ask(input.value); } } }, [input, submit]);

  // `k-chiprow` / `k-chiptog` are the Keep's existing pill-button recipe (hover,
  // 44px target, disabled state). Reused rather than restyled: a second chip
  // class drifts from the first the moment either is touched.
  const chips = suggestionChips(guide);
  chipButtons.push(...chips.map((c) =>
    el("button", { class: "k-chiptog", attrs: { type: "button" },
      // The `disabled` set by setBusy() stops this firing at all; the guard is
      // belt and braces for a click already dispatched when it was set.
      on: { click: () => { if (inFlight) return; input.value = c.ask; ask(c.ask); } }, text: c.ask })));
  const chipRow = chipButtons.length
    ? el("div", { class: "k-chiprow k-help__chips" }, chipButtons)
    : null;

  // `mid` (880px): an answer is prose, and prose set to the Keep's full 1200px
  // measure runs past a comfortable line length — the ask box stretches with it
  // and ends up a 1100px-wide single-line input. Measured at 1280px before the
  // change.
  // Restore the last answer before mounting, so returning from a credited link
  // shows what you left rather than an empty page — but only to the person who
  // asked it. A null owner on either side never matches, which is the safe
  // direction: it costs a restore, not a disclosure.
  const me = getUser()?.id ?? null;
  if (lastAsk && me && lastAsk.owner === me) {
    input.value = lastAsk.question;
    if (lastAsk.shaped.ok) renderAnswer(lastAsk.shaped, lastAsk.question); else renderNotice(lastAsk.shaped);
  }

  mount(page("help", [
    originBackRow(),
    el("h1", { class: "k-h1", text: "Help" }),
    el("p", { class: "k-sub", text: "Ask about anything in the Keep — I'll point you to the right screen, or read back what's on your file." }),
    chipRow,
    form,
    error,
    answerRegion,
  ], { mid: true }));
}
