// keep/views/help-view.js — the Help desk page (#/keep/help, feature 003).
//
// Ask a question in plain language, get an answer from the app's help guide and
// your own records. The page's job beyond rendering is FR-10 and FR-8's UI half:
// it labels every answer AI-generated and offers the broker channel, and it does
// so UNCONDITIONALLY — never off a flag the model controls. Of the three places
// the fact/advice boundary is defended (plan, Key decision 3), this is the ONLY
// independent one: the prompt rules and the shape of the grounding both resolve
// through the same single inference, so they lower the odds and cannot catch a
// violation. This file is what still holds when that inference goes wrong.
import { el, mount } from "../../dom.js";
import { icon } from "../../icons.js";
import { askHelp, loadHelpGuide, getUser } from "../../supabase.js";
import {
  cleanQuestion, validateQuestion, suggestionChips, answerShape, creditedTopics,
} from "../logic/help.js";
import { page, originBackRow } from "./shell.js";

// FR-10's sentence, in ONE place. It is shown up front (before any question, so
// the client knows what they are reading before they type) and again on every
// answer. Two surfaces, one string — a label the user sees only after asking
// cannot inform the decision to ask.
const AI_NOTE =
  "Answers are AI-generated by Anthropic from this app's help guide and a summary " +
  "of your own records — check anything important with your broker.";

// The last answer, kept across navigations. FR-11 invites the client to follow a
// credited source to check it; the back control then promises "Back to help" —
// and the page they returned to was empty, because all state lived in this
// function's closure. Checking the answer cost the answer, and re-asking cost
// another paid call and one of twenty hourly slots.
//
// ⚠️ STAMPED WITH THE OWNER, and restored only to that owner. Module state
// outlives a sign-out: without this, signing out and signing in as someone else
// in the same tab showed the previous client's question, their answer, and their
// record lines under "Based on". This repo publishes three demo credentials and
// the login screen prefills one, so "a different person signs in on this
// machine" is the ordinary case, not a contrived one. Flagged by a security
// review of the commit that added the cache.
let lastAsk = null;


// ⚠️ THE BUSY GATE IS MODULE-LEVEL, and that is the point: `inFlight` below is
// per render, so it could not survive one. Start an ask, navigate away, come
// back before it settles — the new renderKeepHelp() builds a fresh `inFlight =
// null` with every control ENABLED, so a second submit launched a second
// provider call while the first was still running. Repeat the navigation and the
// client is billed for several answers and burns several throttle slots, while
// the UI claims one at a time.
// That harm was already written down a few lines below ("a second ask does not
// replace the first, it adds to it") — it was simply only solved WITHIN a
// render. Found by Codex.
// Keyed on the owner, not a bare boolean: if A's ask is still in flight when B
// signs in on the same tab, B must not be locked out of their own desk.
// Carries `seq` so an earlier ask's completion cannot release a later one's gate.
// Owners with a provider call in flight. ⚠️ A SET, NOT A SINGLE SLOT, and that
// is not tidiness — a single slot had a real hole. `pending = { owner }` is
// overwritten by the next client's ask, so: A asks, A signs out, B signs in and
// asks (overwriting A's entry), A signs back in and asks — and A's gate is gone,
// so A now has TWO live calls whose answers can land out of order. A generation
// token used to sit alongside this to make that safe, and it was the only guard
// with no scenario driving it. Keying the gate properly removes the hole AND the
// need for the token: with this, a second ask by the SAME owner is impossible
// while the first is live, so an out-of-order same-owner pair cannot arise.
// Cross-owner is handled by the owner captured before the await (S14).
// Entries are deleted in a `finally`, so nothing accumulates.
const pendingByOwner = new Set();   // owner ids with a call in flight

// The Help view currently on screen. `ask()` renders its RESULT through this
// rather than through its own closures, because the render that started an ask
// may no longer be the one the client is looking at.
//
// ⚠️ THIS IS A CONSEQUENCE OF THE GATE ABOVE AND HAD TO BE HANDLED WITH IT.
// Navigating away mid-ask and back has always meant the answer renders into the
// FIRST render's nodes, which `mount()` has since detached — so it never reached
// the screen. That was survivable only because the second render's controls were
// enabled and the client could ask again; the gate removes that escape, and
// without this the client would wait, see the controls re-enable, and be shown
// nothing at all. The answer was already in `lastAsk`, so it appeared on the
// next visit to Help — which is not a defence of leaving it there.
let liveView = null;  // { renderAnswer, renderNotice, setBusy, input }

export async function renderKeepHelp() {
  const guide = await loadHelpGuide();

  const input = el("input", {
    class: "k-help__input",
    attrs: { type: "text", placeholder: "Ask a question…", "aria-label": "Ask a question", autocomplete: "off" },
  });
  const submit = el("button", { class: "k-btn k-help__ask", attrs: { type: "submit" } }, [el("span", { text: "Ask" })]);
  const error = el("p", { class: "k-error", attrs: { role: "alert" } });
  const answerRegion = el("div", { class: "k-help__out", attrs: { "aria-live": "polite" } }, [
    el("p", { class: "k-help__ai", text: AI_NOTE }),
  ]);

  // One in-flight request at a time. A second ask aborts the first rather than
  // racing it — two answers arriving out of order would render the older one.
  let inFlight = null;

  // The chips are disabled too, not just the input and the button. Aborting the
  // in-flight request only drops the BROWSER's side of it: the Edge Function has
  // already reserved a throttle row and may have started the provider call, and
  // that keeps running. So a second ask does not replace the first, it adds to
  // it — the UI said "one in flight" while the client was billed for several and
  // burned several throttle slots. Populated by renderChips() below, which runs
  // after this is defined.
  const chipButtons = [];
  function setBusy(busy) {
    submit.disabled = busy;
    input.disabled = busy;
    for (const b of chipButtons) b.disabled = busy;
    submit.querySelector("span").textContent = busy ? "Asking…" : "Ask";
  }

  function renderNotice(shaped) {
    answerRegion.replaceChildren(
      el("div", { class: "k-help__notice" }, [
        icon("alert", { size: 18 }),
        el("p", { text: shaped.notice }),
      ]),
      // The standing label lives IN this region, so replacing the region removed
      // it — leaving the failure state as the one screen with no AI-generated
      // line on it. Re-rendered rather than moved out, so there is still exactly
      // one on screen in every state.
      el("p", { class: "k-help__ai", text: AI_NOTE }),
    );
  }

  function renderAnswer(shaped, question) {
    const used = creditedTopics(guide, shaped.topics);
    const blocks = [
      el("p", { class: "k-help__q", text: question }),
      // `white-space: pre-line` in keep.css — the answer may carry line breaks
      // and collapsing them would run separate points together.
      el("div", { class: "k-help__a" }, [el("p", { text: shaped.answer })]),
    ];

    // FR-11: name what it drew on, so the client can check it.
    if (used.length || shaped.records.length) {
      blocks.push(el("div", { class: "k-help__src" }, [
        el("div", { class: "k-lbl", text: "Based on" }),
        ...used.map((t) => el("a", { class: "k-ilink", attrs: { href: t.route }, text: t.title })),
        ...shaped.records.map((r) => el("span", { class: "k-imuted", text: r })),
      ]));
    }

    // FR-8's hand-off, on EVERY answer. Nothing reads `reason === "refused"` here
    // and nothing should: the model sets it, so gating the remedy on it let a
    // model answer a coverage question AND attach "this needs your broker"
    // underneath, which reads as broker-endorsed. The trailer still carries it
    // and the payload still reports it — for logging and for anyone auditing how
    // often the boundary fires — but it decides nothing the client sees.
    //
    // That flag is model-controlled end to end: the model emits the REFUSED
    // marker, the function turns it into `reason: "refused"`, help.js turns that
    // into `brokerHandoff`, and this block appeared. Both error directions are
    // reachable and one is worse than having no hand-off at all:
    //   · declines in prose, omits the marker → the client is refused with no
    //     broker channel, so FR-8's remedy is silently absent;
    //   · answers a coverage question AND emits the marker → "This one needs your
    //     broker" renders UNDERNEATH a coverage determination, which reads as
    //     broker-endorsed. Measured. And a client can ask for that marker.
    // Unconditional removes both, and a standing "your broker can put it in
    // writing" is the right thing on an insurance help desk anyway. `reason`
    // still carries the distinction for anyone who needs it; nothing the model
    // says decides what the client is offered.
    blocks.push(el("div", { class: "k-help__broker" }, [
      el("p", { text: "Coverage questions — whether something is covered, or whether a limit is enough — are your broker's to answer in writing." }),
      el("a", { class: "k-ilink", attrs: { href: "#/keep/insurance" }, text: "Open a policy to send a request" }),
    ]));

    // FR-10, rendered on EVERY answer regardless of what came back. A model that
    // ignored its instructions cannot remove this line, which is the point.
    blocks.push(el("p", { class: "k-help__ai", text: AI_NOTE }));
    answerRegion.replaceChildren(...blocks);
  }

  async function ask(raw) {
    // cleanQuestion, NOT the raw value: validate and send the SAME string, so the
    // length the client reports is the length the server enforces
    // (`handler.ts`'s QUESTION_MAX, measured after its own trim).
    //
    // ⚠️ This comment previously described a `help_queries` CHECK constraint
    // capping the RAW text, and a correction was then inserted INTO THE MIDDLE OF
    // ITS SENTENCE, leaving "…so validating one / ⚠️ … / string and sending
    // another…". Both the constraint and the column are gone, and a half-applied
    // fix reads worse than the stale text it was patching.
    const question = cleanQuestion(raw);
    const v = validateQuestion(question);
    error.textContent = v.ok ? "" : v.error;
    if (!v.ok) { input.focus(); return; }

    // ⚠️ THE OWNER IS CAPTURED HERE, BEFORE THE AWAIT — not read after it. This
    // line used to be `owner: getUser()?.id` down beside the cache write, and
    // that is a cross-client disclosure, not a tidiness point: the provider call
    // runs for up to 60s and nothing aborts it when the client signs out (only a
    // NEWER ask aborts, via the controller below). So client A asks, signs out,
    // client B signs in on the same tab before the call returns — and the cache
    // stamped A's question, answer and credited RECORD VALUES with B's id, after
    // which the restore check below matched for B and showed them to B.
    // Found by Codex. It is the same hole a security review caught once already
    // (the cache originally carried no owner at all, which is why the stamp
    // exists); reading the stamp a tick too late reopened it, which is why S14
    // now drives the whole race with a held response rather than asserting on
    // the field's presence.
    const asker = getUser()?.id ?? null;
    // REFUSE rather than supersede. Superseding still bills the first call — the
    // Edge Function keeps going whatever the browser does — so the only thing
    // that actually protects spend is not sending the second one.
    if (pendingByOwner.has(asker)) return;
    pendingByOwner.add(asker);

    if (inFlight) inFlight.abort();
    const controller = new AbortController();
    inFlight = controller;
    setBusy(true);
    // The AI label rides along: replacing the whole region removed it for the
    // length of the request (up to the provider timeout), while this file's own
    // header and S10 both describe it as unconditional. "Unconditional" has to
    // include the state the client spends the most time looking at.
    answerRegion.replaceChildren(
      el("p", { class: "k-imuted", text: "Looking…" }),
      el("p", { class: "k-help__ai", text: AI_NOTE }),
    );

    let payload;
    try {
      payload = await askHelp(question, { signal: controller.signal });
    } finally {
      // Release on EVERY exit, including a throw. `askHelp` has a catch-all and
      // returns a shaped payload rather than throwing, so this is insurance
      // against that contract changing — not a live case. It matters because a
      // leaked gate is not a glitch: it locks the client out of the desk
      // entirely until they reload the page.
      pendingByOwner.delete(asker);
    }
    if (controller.signal.aborted) return;        // superseded by a newer ask
    inFlight = null;
    // Through liveView: this render may be the detached one. `?? ` falls back to
    // our own closures so a single render (the ordinary case) is unchanged.
    const view = liveView ?? { renderAnswer, renderNotice, setBusy, input };
    view.setBusy(false);

    // The client who asked is no longer the client who is here: do not cache
    // this answer and do not render it. `lastAsk` is deliberately left alone
    // rather than cleared — whatever the CURRENT client has is theirs, and
    // wiping it would let a departed client's in-flight request delete it.
    //
    // ⚠️ THIS LINE IS BELT, NOT THE FIX, and saying so is the point: a mutation
    // that removed it while KEEPING the capture above still passed S14. The
    // capture is what closes the hole — `lastAsk.owner` is then A's id, so the
    // restore check below cannot match for B. This line is kept because it stops
    // a departed client's answer being cached at all, which narrows the window if
    // the restore check is ever loosened — and that check has already been the
    // site of one defect (it originally carried no owner at all). A surviving
    // mutation means defence in depth, so it is labelled as such rather than
    // left looking load-bearing.
    if ((getUser()?.id ?? null) !== asker) return;

    const shaped = answerShape(payload);
    lastAsk = { shaped, question, owner: asker };
    if (shaped.ok) view.renderAnswer(shaped, question); else view.renderNotice(shaped);
    // The ask box of the view on screen, not of the render that asked.
    if (view.input !== input) view.input.value = question;

    // Disabling the focused control drops focus to <body>, and nothing put it
    // back — so after one question a keyboard or screen-reader user had to tab
    // from the top of the page (bar, nav, search, two menus) to ask another.
    // Restored only when WE are the ones who dropped it: if the reader has tabbed
    // somewhere else while waiting, stealing focus back is worse than the bug.
    if (document.activeElement === document.body) view.input.focus();
  }

  const form = el("form", { class: "k-help__form", attrs: { novalidate: "novalidate" },
    on: { submit: (e) => { e.preventDefault(); ask(input.value); } } }, [input, submit]);

  // `k-chiprow` / `k-chiptog` are the Keep's existing pill-button recipe (hover,
  // 44px target, disabled state). Reused rather than restyled: a second chip
  // class drifts from the first the moment either is touched.
  const chips = suggestionChips(guide);
  chipButtons.push(...chips.map((c) =>
    el("button", { class: "k-chiptog", attrs: { type: "button" },
      // The `disabled` set by setBusy() stops this firing at all; the guard is
      // belt and braces for a click already dispatched when it was set.
      on: { click: () => { if (inFlight) return; input.value = c.ask; ask(c.ask); } }, text: c.ask })));
  const chipRow = chipButtons.length
    ? el("div", { class: "k-chiprow k-help__chips" }, chipButtons)
    : null;

  // `mid` (880px): an answer is prose, and prose set to the Keep's full 1200px
  // measure runs past a comfortable line length — the ask box stretches with it
  // and ends up a 1100px-wide single-line input. Measured at 1280px before the
  // change.
  // Restore the last answer before mounting, so returning from a credited link
  // shows what you left rather than an empty page — but only to the person who
  // asked it. A null owner on either side never matches, which is the safe
  // direction: it costs a restore, not a disclosure.
  const me = getUser()?.id ?? null;
  // A render that arrives mid-ask shows the ask as in progress, rather than
  // offering controls that would launch a second paid call. This is the half of
  // the module-level gate the client can see.
  if (me && pendingByOwner.has(me)) setBusy(true);
  // Registered AFTER the restore check so a render that throws before this point
  // cannot become the target for an in-flight answer.
  liveView = { renderAnswer, renderNotice, setBusy, input };
  if (lastAsk && me && lastAsk.owner === me) {
    input.value = lastAsk.question;
    if (lastAsk.shaped.ok) renderAnswer(lastAsk.shaped, lastAsk.question); else renderNotice(lastAsk.shaped);
  }

  mount(page("help", [
    originBackRow(),
    el("h1", { class: "k-h1", text: "Help" }),
    el("p", { class: "k-sub", text: "Ask about anything in the Keep — I'll point you to the right screen, or read back what's on your file." }),
    chipRow,
    form,
    error,
    answerRegion,
  ], { mid: true }));
}
