// notify-lead — Supabase Edge Function (Deno).
//
// Triggered by a Database Webhook on INSERT into public.leads (configured at
// provisioning; see supabase/README.md). It emails the broker a summary of the new
// lead. Deployed and wired only when the project is provisioned — this is prepared,
// not live.
//
// Secrets (set with `supabase secrets set …`, never committed, never shipped to the client):
//   RESEND_API_KEY  — transactional email provider key
//   FROM_EMAIL      — verified sender address (e.g. "leads@yourdomain.com")
//   BROKER_EMAIL    — where new-lead notifications go
//   WEBHOOK_SECRET  — shared secret; the webhook must send it as header "x-webhook-secret"
//
// The email provider is isolated here; swapping Resend for another provider only
// touches sendEmail().

interface LeadRecord {
  id: string;
  created_at: string;
  domain: string;
  industry: string | null;
  answers: Record<string, unknown>;
  needs: Array<{ id: string; title: string; why: string; priority: string }>;
  contact_name: string;
  contact_email: string | null;
  contact_phone: string | null;
  is_partial: boolean;
}

interface WebhookPayload {
  type: string;
  table: string;
  record: LeadRecord;
}

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return json({ error: "method not allowed" }, 405);
  }

  // Reject anything that doesn't present the shared secret.
  const expected = Deno.env.get("WEBHOOK_SECRET");
  if (!expected || req.headers.get("x-webhook-secret") !== expected) {
    return json({ error: "unauthorized" }, 401);
  }

  let payload: WebhookPayload;
  try {
    payload = await req.json();
  } catch {
    return json({ error: "invalid json" }, 400);
  }

  if (payload.type !== "INSERT" || payload.table !== "leads" || !payload.record) {
    // Not a lead insert — acknowledge so the webhook doesn't retry.
    return json({ ignored: true }, 200);
  }

  try {
    await sendEmail(payload.record);
  } catch (err) {
    console.error("notify-lead: email send failed", err);
    return json({ error: "email send failed" }, 502);
  }

  return json({ ok: true }, 200);
});

async function sendEmail(lead: LeadRecord): Promise<void> {
  const apiKey = requireEnv("RESEND_API_KEY");
  const from = requireEnv("FROM_EMAIL");
  const to = requireEnv("BROKER_EMAIL");

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `New ${lead.domain} lead: ${lead.contact_name}${lead.is_partial ? " (partial)" : ""}`,
      text: renderLead(lead),
    }),
  });

  if (!res.ok) {
    throw new Error(`provider responded ${res.status}: ${await res.text()}`);
  }
}

function renderLead(lead: LeadRecord): string {
  const lines: string[] = [];
  lines.push(`New ${lead.domain} lead${lead.is_partial ? " (partial)" : ""}`);
  lines.push("");
  lines.push(`Name:  ${lead.contact_name}`);
  if (lead.contact_email) lines.push(`Email: ${lead.contact_email}`);
  if (lead.contact_phone) lines.push(`Phone: ${lead.contact_phone}`);
  if (lead.industry) lines.push(`Industry: ${lead.industry}`);
  lines.push("");
  lines.push("Suggested coverages to review:");
  for (const need of lead.needs ?? []) {
    lines.push(`  • [${need.priority}] ${need.title} — ${need.why}`);
  }
  lines.push("");
  lines.push("This is a lead generated by the coverage guide — not a quote or bound policy.");
  lines.push(`Lead id: ${lead.id} · received ${lead.created_at}`);
  return lines.join("\n");
}

function requireEnv(name: string): string {
  const value = Deno.env.get(name);
  if (!value) throw new Error(`missing required env var: ${name}`);
  return value;
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
